# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_document', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('traitement', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mension', models.TextField()),
                ('page', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_observation', models.CharField(max_length=200)),
                ('acces_possible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_operation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sondage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_unite', models.CharField(max_length=200)),
                ('couleur_MSCC', models.CharField(max_length=100)),
                ('carbonate', models.BooleanField()),
                ('tache', models.TextField(blank=True, null=True)),
                ('inclusion', models.CharField(max_length=100)),
                ('mobilier', models.TextField(blank=True, null=True)),
                ('perturbation', models.TextField(blank=True, null=True)),
                ('autre', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
