# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.TextField()),
                ('page', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mension',
        ),
        migrations.AddField(
            model_name='observation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(2 47)', srid=4326),
        ),
        migrations.AddField(
            model_name='observation',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.Sequence'),
        ),
        migrations.AddField(
            model_name='observation',
            name='sondage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.Sondage'),
        ),
        migrations.AddField(
            model_name='observation',
            name='type_observation',
            field=models.CharField(choices=[('log', 'log'), ('coupe', 'coupe'), ('plan', 'plan')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('fouille préventive', 'fouille préventive'), ('diagnostic préventif', 'diagnostic préventif'), ('fouille programmée', 'fouille programmée'), ('carrière', 'carrière'), ('autre chantier', 'autre chantier'), ('autre', 'autre')], default='indéfini', max_length=25),
        ),
        migrations.AddField(
            model_name='sequence',
            name='unite',
            field=models.ManyToManyField(to='inventaire.Unite'),
        ),
        migrations.AddField(
            model_name='sondage',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(2 47)', srid=4326),
        ),
        migrations.AddField(
            model_name='sondage',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.Operation'),
        ),
        migrations.AddField(
            model_name='unite',
            name='compacite',
            field=models.CharField(choices=[('très compact', 'très compact'), ('compact', 'compact'), ('peu compact', 'peu compact'), ('meuble', 'meuble'), ('très meuble', 'très meuble')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='couleur',
            field=models.CharField(choices=[('aucune', 'aucune'), ('blanc', 'blanc'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='description_structure',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='echantillon',
            field=models.CharField(default='undéfini', max_length=100),
        ),
        migrations.AddField(
            model_name='unite',
            name='epaisseur',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='unite',
            name='interface',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='interpretation_pedologique',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='interpretation_sedimentaire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='nuance_couleur',
            field=models.CharField(choices=[('aucune', 'aucune'), ('blanc', 'blanc'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='profondeur',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='unite',
            name='sous_structure',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyyédrique', 'polyyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='structure_1',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyyédrique', 'polyyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='structure_2',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyyédrique', 'polyyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='taille_structure',
            field=models.CharField(choices=[('très fine', 'très fine'), ('fine', 'fine'), ('pas de taille particulière', 'pas de taille particulière'), ('grossière', 'grossière'), ('très grossière', 'très grossière')], default='pas de taille particulière', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='texture_1',
            field=models.CharField(choices=[('aucune', 'aucune'), ('caillouteux', 'caillouteux'), ('graveleux', 'graveleux'), ('sableux', 'sableux'), ('limoneux', 'limoneux'), ('argileux', 'argileux')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='texture_2',
            field=models.CharField(choices=[('aucune', 'aucune'), ('caillouteux', 'caillouteux'), ('graveleux', 'graveleux'), ('sableux', 'sableux'), ('limoneux', 'limoneux'), ('argileux', 'argileux')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='type_carbon',
            field=models.CharField(choices=[('masse fine', 'masse fine'), ('secondaire', 'secondaire'), ('poupées', 'poupées'), ('pseudo-mycélium', 'pseudo-mycélium')], default='indéfini', max_length=50),
        ),
        migrations.AddField(
            model_name='unite',
            name='valeur_couleur',
            field=models.CharField(choices=[('très sombre', 'très sombre'), ('sombre', 'sombre'), ('pas de valeur particulière', 'pas de valeur particulière'), ('clair', 'clair'), ('très clair', 'très clair')], default='pas de valeur particulière', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='annee',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2016)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='nom_document',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nom_observation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operation',
            name='nom_operation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='nom_sequence',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='nom_sondage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unite',
            name='inclusion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unite',
            name='nom_unite',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='mention',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.Document'),
        ),
        migrations.AddField(
            model_name='mention',
            name='sequence',
            field=models.ManyToManyField(to='inventaire.Sequence'),
        ),
    ]
