# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_auto_20160127_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
