# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_auto_20160111_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='mension',
            field=models.ManyToManyField(to='inventaire.Mension'),
        ),
    ]
