# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_auto_20160127_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='geom',
        ),
        migrations.AddField(
            model_name='operation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='unite',
            name='couleur',
            field=models.CharField(choices=[('aucune', 'aucune'), ('blanc', 'blanc'), ('gris', 'gris'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille')], default='indéfini', max_length=50),
        ),
        migrations.AlterField(
            model_name='unite',
            name='description_structure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unite',
            name='inclusion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unite',
            name='interpretation_pedologique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unite',
            name='interpretation_sedimentaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unite',
            name='nuance_couleur',
            field=models.CharField(choices=[('aucune', 'aucune'), ('blanc', 'blanc'), ('gris', 'gris'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille')], default='indéfini', max_length=50),
        ),
        migrations.AlterField(
            model_name='unite',
            name='sous_structure',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyédrique', 'polyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=50),
        ),
        migrations.AlterField(
            model_name='unite',
            name='structure_1',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyédrique', 'polyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=50),
        ),
        migrations.AlterField(
            model_name='unite',
            name='structure_2',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyédrique', 'polyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=50),
        ),
        migrations.AlterField(
            model_name='unite',
            name='type_carbon',
            field=models.CharField(choices=[('masse fine', 'masse fine'), ('secondaire', 'secondaire'), ('poupées', 'poupées'), ('pseudo-mycélium', 'pseudo-mycélium'), ('aucune', 'aucune')], default='indéfini', max_length=50),
        ),
        migrations.AlterField(
            model_name='unite',
            name='valeur_couleur',
            field=models.CharField(choices=[('très sombre', 'très sombre'), ('sombre', 'sombre'), ('aucune', 'aucune'), ('clair', 'clair'), ('très clair', 'très clair')], default='aucune', max_length=50),
        ),
    ]
