# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_auto_20160111_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='type_obs',
            new_name='type_observation',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='type_op',
            new_name='type_operation',
        ),
        migrations.AlterField(
            model_name='unite',
            name='couleur',
            field=models.CharField(choices=[('blanc', 'blanc'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille'), ('clair', 'clair')], default='indéfini', max_length=10),
        ),
        migrations.AlterField(
            model_name='unite',
            name='structure',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyyédrique', 'polyyédrique'), ('prismatique', 'prismatique'), ('grossière', 'grossière'), ('fine', 'fine')], default='indéfini', max_length=20),
        ),
        migrations.AlterField(
            model_name='unite',
            name='texture',
            field=models.CharField(choices=[('caillouteux', 'caillouteux'), ('graveleux', 'graveleux'), ('sableux', 'sableux'), ('limoneux', 'limoneux'), ('argileux', 'argileux')], default='indéfini', max_length=20),
        ),
    ]
