# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0008_auto_20160111_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mention', models.TextField()),
                ('page', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.Document')),
                ('sequence', models.ManyToManyField(to='inventaire.Sequence')),
            ],
        ),
        migrations.RemoveField(
            model_name='mension',
            name='Sequence',
        ),
        migrations.RemoveField(
            model_name='mension',
            name='document',
        ),
        migrations.DeleteModel(
            name='Mension',
        ),
    ]
