# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0009_auto_20160112_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unite',
            name='autre',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='carbonate',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='couleur_MSCC',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='inclusion',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='mobilier',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='perturbation',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='taches',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='texture',
        ),
    ]
