# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0010_auto_20160122_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='autre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='carbonate',
            field=models.BooleanField(default='false'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unite',
            name='compacite',
            field=models.CharField(choices=[('très compact', 'très compact'), ('compact', 'compact'), ('peu compact', 'peu compact'), ('meuble', 'meuble'), ('très meuble', 'très meuble')], default='indéfini', max_length=20),
        ),
        migrations.AddField(
            model_name='unite',
            name='couleur',
            field=models.CharField(choices=[('aucune', 'aucune'), ('blanc', 'blanc'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille')], default='indéfini', max_length=10),
        ),
        migrations.AddField(
            model_name='unite',
            name='couleur_MSCC',
            field=models.CharField(default='indefini', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unite',
            name='description_structure',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='echantillon',
            field=models.CharField(default='indefini', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unite',
            name='inclusion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='interface',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='interpretation_pedologique',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='interpretation_sedimentaire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='mobilier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='nuance_couleur',
            field=models.CharField(choices=[('aucune', 'aucune'), ('blanc', 'blanc'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille')], default='indéfini', max_length=10),
        ),
        migrations.AddField(
            model_name='unite',
            name='perturbation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='sous_structure',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyyédrique', 'polyyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=20),
        ),
        migrations.AddField(
            model_name='unite',
            name='structure_1',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyyédrique', 'polyyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=20),
        ),
        migrations.AddField(
            model_name='unite',
            name='structure_2',
            field=models.CharField(choices=[('massive', 'massive'), ('lamellaire', 'lamellaire'), ('polyyédrique', 'polyyédrique'), ('prismatique', 'prismatique'), ('grumeleuse', 'grumeleuse'), ('grenue', 'grenue')], default='indéfini', max_length=20),
        ),
        migrations.AddField(
            model_name='unite',
            name='taches',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='taille_structure',
            field=models.CharField(choices=[('très fine', 'très fine'), ('fine', 'fine'), ('pas de taille particulière', 'pas de taille particulière'), ('grossière', 'grossière'), ('très grossière', 'très grossière')], default='indéfini', max_length=20),
        ),
        migrations.AddField(
            model_name='unite',
            name='texture_1',
            field=models.CharField(choices=[('aucune', 'aucune'), ('caillouteux', 'caillouteux'), ('graveleux', 'graveleux'), ('sableux', 'sableux'), ('limoneux', 'limoneux'), ('argileux', 'argileux')], default='indéfini', max_length=20),
        ),
        migrations.AddField(
            model_name='unite',
            name='texture_2',
            field=models.CharField(choices=[('aucune', 'aucune'), ('caillouteux', 'caillouteux'), ('graveleux', 'graveleux'), ('sableux', 'sableux'), ('limoneux', 'limoneux'), ('argileux', 'argileux')], default='indéfini', max_length=20),
        ),
        migrations.AddField(
            model_name='unite',
            name='type_carbon',
            field=models.CharField(choices=[('masse fine', 'masse fine'), ('secondaire', 'secondaire'), ('poupées', 'poupées'), ('pseudo-mycélium', 'pseudo-mycélium')], default='indéfini', max_length=10),
        ),
        migrations.AddField(
            model_name='unite',
            name='valeur_couleur',
            field=models.CharField(choices=[('très sombre', 'très sombre'), ('sombre', 'sombre'), ('pas de valeur particulière', 'pas de valeur particulière'), ('clair', 'clair'), ('très clair', 'très clair')], default='indéfini', max_length=10),
        ),
    ]
