# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0011_auto_20160122_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='epaisseur',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='unite',
            name='profondeur',
            field=models.FloatField(default=0.0),
        ),
    ]
