# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0012_auto_20160123_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='couleur',
            field=models.CharField(choices=[('aucune', 'aucune'), ('blanc', 'blanc'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille')], default='indéfini', max_length=20),
        ),
        migrations.AlterField(
            model_name='unite',
            name='nuance_couleur',
            field=models.CharField(choices=[('aucune', 'aucune'), ('blanc', 'blanc'), ('noir', 'noir'), ('brun', 'brun'), ('jaune', 'jaune'), ('orange', 'orange'), ('rouge', 'rouge'), ('vert', 'vert'), ('bleu', 'bleu'), ('rouille', 'rouille')], default='indéfini', max_length=20),
        ),
        migrations.AlterField(
            model_name='unite',
            name='type_carbon',
            field=models.CharField(choices=[('masse fine', 'masse fine'), ('secondaire', 'secondaire'), ('poupées', 'poupées'), ('pseudo-mycélium', 'pseudo-mycélium')], default='indéfini', max_length=20),
        ),
        migrations.AlterField(
            model_name='unite',
            name='valeur_couleur',
            field=models.CharField(choices=[('très sombre', 'très sombre'), ('sombre', 'sombre'), ('pas de valeur particulière', 'pas de valeur particulière'), ('clair', 'clair'), ('très clair', 'très clair')], default='indéfini', max_length=20),
        ),
    ]
