# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0013_auto_20160123_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='taille_structure',
            field=models.CharField(choices=[('très fine', 'très fine'), ('fine', 'fine'), ('pas de taille particulière', 'pas de taille particulière'), ('grossière', 'grossière'), ('très grossière', 'très grossière')], default='pas de taille particulière', max_length=20),
        ),
        migrations.AlterField(
            model_name='unite',
            name='valeur_couleur',
            field=models.CharField(choices=[('très sombre', 'très sombre'), ('sombre', 'sombre'), ('pas de valeur particulière', 'pas de valeur particulière'), ('clair', 'clair'), ('très clair', 'très clair')], default='pas de valeur particulière', max_length=20),
        ),
    ]
