# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_auto_20160111_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='annee',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
