# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0014_auto_20160123_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='id',
        ),
        migrations.AlterField(
            model_name='sequence',
            name='nom_sequence',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
