# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0015_auto_20160124_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='indefini', srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sondage',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='indefini', srid=4326),
            preserve_default=False,
        ),
    ]
